// Code generated by mockery v2.14.0. DO NOT EDIT.

package mock

import (
	models "github.com/hugohenrick/gtasks/models"
	mock "github.com/stretchr/testify/mock"
)

// ITaskRepository is an autogenerated mock type for the ITaskRepository type
type ITaskRepository struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: task
func (_m *ITaskRepository) CreateTask(task models.Task) (models.Task, error) {
	ret := _m.Called(task)

	var r0 models.Task
	if rf, ok := ret.Get(0).(func(models.Task) models.Task); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: id
func (_m *ITaskRepository) DeleteTask(id string) (int64, error) {
	ret := _m.Called(id)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecuteTask provides a mock function with given fields: id, task
func (_m *ITaskRepository) ExecuteTask(id string, task models.Task) (models.Task, error) {
	ret := _m.Called(id, task)

	var r0 models.Task
	if rf, ok := ret.Get(0).(func(string, models.Task) models.Task); ok {
		r0 = rf(id, task)
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, models.Task) error); ok {
		r1 = rf(id, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTaskById provides a mock function with given fields: id
func (_m *ITaskRepository) FindTaskById(id string) (models.Task, error) {
	ret := _m.Called(id)

	var r0 models.Task
	if rf, ok := ret.Get(0).(func(string) models.Task); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTasks provides a mock function with given fields: task
func (_m *ITaskRepository) FindTasks(task models.Task) ([]models.Task, error) {
	ret := _m.Called(task)

	var r0 []models.Task
	if rf, ok := ret.Get(0).(func(models.Task) []models.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: id, task
func (_m *ITaskRepository) UpdateTask(id string, task models.Task) (models.Task, error) {
	ret := _m.Called(id, task)

	var r0 models.Task
	if rf, ok := ret.Get(0).(func(string, models.Task) models.Task); ok {
		r0 = rf(id, task)
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, models.Task) error); ok {
		r1 = rf(id, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewITaskRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewITaskRepository creates a new instance of ITaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewITaskRepository(t mockConstructorTestingTNewITaskRepository) *ITaskRepository {
	mock := &ITaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
