
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gtasks
spec:
  selector:
    matchLabels:
      app.kubernetes.io/workload: api-gtasks
  template:
    metadata:
      labels:
        app.kubernetes.io/workload: api-gtasks
    spec:
      containers:
      - name: gtasks
        image: hugohenrick/gtasks:v1.0
        ports:
        - containerPort: 8080
              
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/workload: api-gtasks
  name: api-gtasks
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/workload: api-gtasks
  type: ClusterIP